# config/training.yaml

training:
  num_epochs: 10
  batch_size: 128
  learning_rate: 3.0e-4
  weight_decay: 1.0e-5
  clip_grad_norm: 3.0
  
  # Scheduler
  use_lr_scheduler: true
  lr_scheduler_factor: 0.5
  lr_scheduler_patience: 2
  
  # Evaluation
  eval_every: 5
  bleu_every: 5
  max_bleu_samples: null  # Use all samples
  
  # Early stopping
  early_stopping_patience: 5
  
  # Logging
  print_frequency: 100
  save_best_only: true
  save_frequency: 1
  
  # Debug overrides
  debug:
    num_epochs: 3
    batch_size: 8
    max_bleu_samples: 50
    print_frequency: 5